"""Ablation: does every field in RCDR earn its place?

A format is easy to pad. The honest test is to delete each field from a record that
supports C2, re-run the verifier, and record what capability dies. A field that can be
removed without changing the answer is decoration, and should be cut from v0.2.

This is a test of our own necessity, and it is cheap here only because the verifier is
already the ablation engine — §5.1 is a decision procedure, so "what breaks" is computed
rather than argued.

Run with:  python -m demo.ablation      (from the repository root)
"""

import copy
from pathlib import Path

from reckon import MemorySink, Recorder, verify_run

# Each entry is the dotted path deleted from an otherwise C2-complete record.
ABLATIONS = [
    "execution.runtime",
    "execution.deps_digest",
    "execution.path_digest",
    "execution.pure",
    "predicate.id",
    "compared.value",
    "policy.resolved_value",
    "policy.resolution.provenance",
    "candidates.completeness",
    "candidates.items",
    "action.params_digest",
    "capture.sdk_version",
    "ts",
]


def complete_record() -> dict:
    sink = MemorySink()
    rec = Recorder(sink=sink, run_id="ablation", emitter="ablation")
    with rec.decision(action="transfer", pure=True) as d:
        d.policy("policy.limit", value=5000, provenance="bundled", source="opa:bundle")
        allowed = d.check("lt", left="request.amount", value=4200, right="policy.limit")
        d.candidate("transfer", compared_value=4200, outcome="admit", predicate="p:limit")
        d.candidate("hold", compared_value=4200, outcome="reject", predicate="p:limit")
        d.candidates_exhaustive()
        d.admit() if allowed else d.reject()
    return sink.records[0]


def delete(record: dict, path: str) -> dict:
    ablated = copy.deepcopy(record)
    node = ablated
    parts = path.split(".")
    for part in parts[:-1]:
        node = node[part]
    node.pop(parts[-1], None)
    return ablated


def highest_class(record: dict) -> str | None:
    return verify_run([record], requested="C2").available


def run() -> list[tuple[str, str | None]]:
    baseline = complete_record()
    assert highest_class(baseline) == "C2", "baseline must support C2"
    return [(path, highest_class(delete(baseline, path))) for path in ABLATIONS]


def render(results: list[tuple[str, str | None]]) -> str:
    lines = [
        "| Field removed | Highest class still supported | What is lost |",
        "|---|---|---|",
    ]
    for path, available in results:
        lost = {
            None: "everything — the record cannot even be replayed as itself",
            "C0": "re-adjudication under any different policy",
            "C1": "re-adjudication under a *looser* policy",
            "C2": "**nothing — this field is decoration**",
        }[available]
        lines.append(f"| `{path}` | {available or 'none'} | {lost} |")
    return "\n".join(lines)


def main() -> None:
    results = run()
    print("Baseline: a complete record supports C2.\n")
    print(render(results))

    decorative = [path for path, available in results if available == "C2"]
    print(
        f"\n{len(results) - len(decorative)} of {len(results)} fields are load-bearing. "
        f"{len(decorative)} are not: {', '.join(decorative) or 'none'}."
    )
    print(
        "\nThe non-load-bearing fields are kept deliberately: they carry ordering and\n"
        "human-readable context, and none of them is consulted by §5.1.\n"
        "A verifier that gated on them would be claiming evidence it does not have."
    )

    out = Path(__file__).parent / "ABLATION.md"
    out.write_text(
        "# Ablation — does every field earn its place?\n\n"
        "Generated by `python -m demo.ablation`. Each row deletes one field from a record\n"
        "that supports C2 and re-runs the verifier.\n\n"
        f"{render(results)}\n\n"
        f"{len(results) - len(decorative)} of {len(results)} fields are load-bearing.\n\n"
        "The rest are kept deliberately — they carry attribution and human-readable context\n"
        "for someone reading a run, and §5.1 never consults them. A verifier gating on them\n"
        "would be claiming evidence it does not have.\n\n"
        "## The design law\n\n"
        "> **No record carries its own soundness proof.**\n\n"
        "Every load-bearing field above exists because some real system omitted it and\n"
        "nothing in its record revealed the omission.\n"
    )
    print(f"\nWritten to {out}")


if __name__ == "__main__":
    main()
